import math
SWIDTH=800
SHEIGHT=600
BORDERWIDTH=32
LOWERBORDER=150
screensize=[SWIDTH,SHEIGHT]
IW=53
IH=68
SCREENPLAYDIAG = math.sqrt((SWIDTH-BORDERWIDTH*2)*(SWIDTH-BORDERWIDTH*2)+(SHEIGHT-80-BORDERWIDTH)*(SHEIGHT-80-BORDERWIDTH))


